[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra
filterwarnings =
    ignore:The 'app' shortcut is now deprecated.*:DeprecationWarning:httpx\._client
    ignore:PyPDF2 is deprecated.*:DeprecationWarning:PyPDF2
