"""Domain objects for review processing."""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(slots=True)
class Clause:
    """A structured clause extracted from a contract."""

    clause_id: str
    title: str
    text: str
    source_index: int


@dataclass(slots=True)
class ParsedDocument:
    """A parsed document ready for clause splitting and analysis."""

    document_id: str
    document_name: str
    content_type: str
    text: str
    clauses: list[Clause] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class RiskDetection:
    """A raw risk detection generated by the rule engine."""

    risk_type: str
    risk_level: str
    rule_name: str
    evidence: list[str] = field(default_factory=list)


@dataclass(slots=True)
class RiskReference:
    """A structured legal reference attached to one risk result."""

    title: str
    source: str
    content: str


@dataclass(slots=True)
class RiskAnalysis:
    """A structured risk analysis result for one clause."""

    clause_id: str
    clause_title: str
    clause_text: str
    risk_type: str
    risk_level: str
    risk_reason: str
    impact_analysis: str
    suggestion: str
    replacement_text: str
    references: list[RiskReference] = field(default_factory=list)


@dataclass(slots=True)
class Review:
    """A persisted contract review result."""

    review_id: str
    document_id: str
    document_name: str
    summary: str
    risks: list[RiskAnalysis]
    created_at: datetime


@dataclass(slots=True)
class ReviewListItem:
    """Compact review information for history listing."""

    review_id: str
    document_id: str
    document_name: str
    summary: str
    created_at: datetime
    risk_counts: dict[str, int]


@dataclass(slots=True)
class ReviewListFilters:
    """Optional filters for history listing queries."""

    document_name: str | None = None
    date_from: datetime | None = None
    date_to: datetime | None = None
    risk_level: str | None = None
